# è¡¨ç¤ºã•ã‚Œã‚‹é …ç›®ã®é †åºã®è¨­å®š(åŸºæœ¬ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã§è‰¯ã„)
prompt_order = [
    "username",
    "directory",
    "line_break", #æ”¹è¡Œã‚’å…¥ã‚ŒãŸã„ä½ç½®ã«è¿½åŠ 
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "character"
]

[battery]
full_symbol = "ðŸ”‹"
charging_symbol = "ðŸ”Œ"
discharging_symbol = "âš¡"

[character]
symbol = "$" # æ–‡å­—ã‚’å¤‰æ›´(ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¯ > )

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "â€¦/"

[shell]
disabled = false
powershell_indicator = "ï‘ _"

[time]
disabled = false
time_format = "%T"
format = "ðŸ•™ $time($style) "
style = "bright-white"

[hostname]
disabled = true

[username]
disabled = true

[python]
disabled = true

format = "[$symbol$version]($style) "
style = "bold green"